#!/bin/bash
source_folder=$1
target_folder=$2

echo "$source_folder"
echo "$target_folder"

#set IFS to newline only
OIFS="$IFS"
IFS=$'\n'

targets=($(grep -Rh "\!\[\[" "$source_folder"))

for ((i = 0; i < "${#targets[@]}"; i++))
do
    echo "${targets[$i]}"
done

#reset IFS
IFS="$OIFS"
