#!/bin/bash

print_usage() {
    printf "usage: writeup-converter [OPTIONS] [source_folder] [source_attachments] [target_folder] [target_attachments]\n\toptions:\n\t\t-p|--prefix    Prefix to exclude in copied version\n"
}

#get flags
while getopts "h:p:" flag; do
case "$flag" in
    p|--prefix)
    prefix=$OPTARG;;
    h|--help)
    print_usage
    exit 1 ;;
esac
done

#get positional arguments
source_folder=${@:$OPTIND:1}
source_attachments=${@:$OPTIND+1:1}
target_folder=${@:$OPTIND+2:1}
target_attachments=${@:$OPTIND+3:1}

echo $prefix

#set IFS to newline only
OIFS="$IFS"
IFS=$'\n'

targets=($(grep -Rh "\!\[\[" "$source_folder"))

#equivalent to sed /\!\[\[|\]\]//

targets=("${targets[@]/![[/}")
targets=("${targets[@]/]]/}")

echo "cp $source_folder $target_folder"
#cp -r $source_folder $target_folder

for ((i = 0; i < "${#targets[@]}"; i++))
do
    echo "Copy $source_attachments${targets[$i]} to $target_attachments"
    #cp $source_attachments${targets[$i]} $target_attachments
done

#reset IFS
IFS="$OIFS"
