#!/bin/bash
source_folder=$1
source_attachments=$2
target_folder=$3
target_attachments=$4

#set IFS to newline only
OIFS="$IFS"
IFS=$'\n'

targets=($(grep -Rh "\!\[\[" "$source_folder"))

#equivalent to sed /\!\[\[|\]\]//

targets=("${targets[@]/![[/}")
targets=("${targets[@]/]]/}")

echo "cp $source_folder $target_folder"
cp -r $source_folder $target_folder

for ((i = 0; i < "${#targets[@]}"; i++))
do
    echo "Copy $source_attachments${targets[$i]} to $target_attachments"
    cp $source_attachments${targets[$i]} $target_attachments
done

#reset IFS
IFS="$OIFS"
